# Generated by Django 6.0.6 on 2026-06-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('censeur', 'Censeur'), ('proviseur', 'Proviseur'), ('surveillant', 'Surveillant'), ('personnel', 'Personnel')], default='personnel', max_length=20, verbose_name='rôle'),
        ),
    ]
