# Generated by Django 6.0.6 on 2026-06-27 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('proprietaire', 'Propriétaire'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('censeur', 'Censeur'), ('proviseur', 'Proviseur'), ('surveillant', 'Surveillant'), ('personnel', 'Personnel')], default='personnel', max_length=20, verbose_name='rôle'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schools', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'école',
                'verbose_name_plural': 'écoles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('proprietaire', 'Propriétaire'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('censeur', 'Censeur'), ('proviseur', 'Proviseur'), ('surveillant', 'Surveillant'), ('personnel', 'Personnel')], max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ekdschoolmanager.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adhésion à une école',
                'verbose_name_plural': 'adhésions aux écoles',
                'ordering': ['school', 'user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'user'), name='unique_school_user')],
            },
        ),
    ]
