# Generated by Django 6.0.6 on 2026-06-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0004_alter_customuser_role_school_schoolmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='logo'),
        ),
    ]
