# Generated by Django 6.0.6 on 2026-06-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0005_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('code', models.SlugField(max_length=40, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'), models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school')],
            },
        ),
    ]
