# Generated by Django 6.0.6 on 2026-06-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0006_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('division_system', models.CharField(choices=[('trimestre', 'Trimestres'), ('semestre', 'Semestres')], default='trimestre', max_length=12, verbose_name='découpage')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_closed', models.BooleanField(default=False, verbose_name='clôturée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'année académique',
                'verbose_name_plural': 'années académiques',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='numéro')),
                ('name', models.CharField(max_length=40, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_closed', models.BooleanField(default=False, verbose_name='clôturée')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='ekdschoolmanager.academicyear')),
            ],
            options={
                'verbose_name': 'période académique',
                'verbose_name_plural': 'périodes académiques',
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='one_active_academic_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academic_year_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='unique_period_number_per_year'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='period_end_after_start'),
        ),
    ]
