# Generated by Django 6.0.6 on 2026-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0007_academicyear_academicperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year',), name='one_active_period_per_academic_year'),
        ),
    ]
