# Generated by Django 6.0.6 on 2026-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0009_activate_first_period'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_closed', True), _negated=True), name='closed_academic_year_cannot_be_active'),
        ),
    ]
