# Generated by Django 6.0.6 on 2026-06-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0010_academicyear_closed_academic_year_cannot_be_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=50, unique=True, verbose_name='matricule')),
                ('status', models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulée')], default='active', max_length=12, verbose_name='statut')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='date d’inscription')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='ekdschoolmanager.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='ekdschoolmanager.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription d’élève',
                'verbose_name_plural': 'inscriptions d’élèves',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'student'), name='unique_student_enrollment_per_year')],
            },
        ),
    ]
