# Generated by Django 6.0.6 on 2026-06-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0011_customuser_address_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
                ('stage', models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], max_length=12, verbose_name='cycle')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'niveau scolaire',
                'verbose_name_plural': 'niveaux scolaires',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='ekdschoolmanager.schoollevel', verbose_name='niveau'),
        ),
        migrations.AddConstraint(
            model_name='schoollevel',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_level_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoollevel',
            constraint=models.UniqueConstraint(fields=('school', 'order'), name='unique_level_order_per_school'),
        ),
    ]
