# Generated by Django 6.0.6 on 2026-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0014_switch_authentication_to_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_number',
            field=models.CharField(max_length=50, verbose_name='matricule'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('school', 'enrollment_number'), name='unique_enrollment_number_per_school'),
        ),
    ]
