# Generated by Django 6.0.6 on 2026-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0025_alter_customuser_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='maximum_capacity',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='capacité maximale'),
        ),
    ]
