# Generated by Django 6.0.6 on 2026-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0026_schoolclass_maximum_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('redoublant', 'Redoublant'), ('abandon', 'Abandon'), ('bachelier', 'Bachelier')], default='nouveau', max_length=12, verbose_name='statut de l’élève'),
        ),
    ]
