# Generated by Django 6.0.6 on 2026-06-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0027_alter_customuser_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='previous_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne scolaire de l’année écoulée'),
        ),
    ]
