# Generated by Django 6.0.6 on 2026-06-28 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0028_studentenrollment_previous_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarded_student_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='tuteur'),
        ),
    ]
