# Generated by Django 6.0.6 on 2026-06-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0029_customuser_profession_studentenrollment_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='allergies'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='health_issues',
            field=models.TextField(blank=True, verbose_name='soucis de santé'),
        ),
    ]
