# Generated by Django 6.0.6 on 2026-06-28 23:29

from django.db import migrations, models


def merge_health_fields(apps, schema_editor):
    CustomUser = apps.get_model('ekdschoolmanager', 'CustomUser')
    for user in CustomUser.objects.exclude(allergies='').exclude(health_issues='').iterator():
        user.health_information = f"Allergies : {user.allergies}\nSoucis de santé : {user.health_issues}"
        user.save(update_fields=['health_information'])
    for user in CustomUser.objects.exclude(allergies='').filter(health_issues='').iterator():
        user.health_information = user.allergies
        user.save(update_fields=['health_information'])
    for user in CustomUser.objects.filter(allergies='').exclude(health_issues='').iterator():
        user.health_information = user.health_issues
        user.save(update_fields=['health_information'])


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0030_customuser_allergies_customuser_health_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health_information',
            field=models.TextField(blank=True, verbose_name='allergies et soucis de santé'),
        ),
        migrations.RunPython(merge_health_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customuser',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='health_issues',
        ),
    ]
