# Generated by Django 6.0.6 on 2026-06-29 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0034_tuition_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant masculin')),
                ('female_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant féminin')),
                ('payable_in_installments', models.BooleanField(default=False, verbose_name='payable en tranches')),
            ],
            options={
                'ordering': ['fee_module__name'],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pourcentage')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('paid_on', models.DateField(verbose_name='date de paiement')),
                ('method', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('banque', 'Banque'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeerule',
            name='unique_tuition_rule_criteria',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeerule',
            name='tuition_rule_has_criterion',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeerule',
            name='rule_tuition_fee_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeerule',
            name='rule_registration_fee_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='tuitioninstallment',
            name='unique_installment_order_per_plan',
        ),
        migrations.RemoveConstraint(
            model_name='tuitioninstallment',
            name='installment_percentage_range',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionpayment',
            name='tuition_payment_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionpayment',
            name='payment_installment_matches_fee_type',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeeplan',
            name='tuition_fee_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='tuitionfeeplan',
            name='registration_fee_non_negative',
        ),
        migrations.AddField(
            model_name='classfeeitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ekdschoolmanager.tuitionfeeplan'),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='class_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='ekdschoolmanager.classfeeitem'),
        ),
        migrations.AddField(
            model_name='feemodule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_modules', to='ekdschoolmanager.academicyear'),
        ),
        migrations.AddField(
            model_name='feemodule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_modules', to='ekdschoolmanager.school'),
        ),
        migrations.AddField(
            model_name='classfeeitem',
            name='fee_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fee_items', to='ekdschoolmanager.feemodule'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='class_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ekdschoolmanager.classfeeitem'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='ekdschoolmanager.studentenrollment'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ekdschoolmanager.feeinstallment'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tuitionfeerule',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tuitioninstallment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tuitionpayment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='tuitionpayment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='tuitionpayment',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='tuitionfeeplan',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='tuitionfeeplan',
            name='tuition_fee',
        ),
        migrations.AddConstraint(
            model_name='feeinstallment',
            constraint=models.UniqueConstraint(fields=('class_fee', 'order'), name='unique_installment_order_per_class_fee'),
        ),
        migrations.AddConstraint(
            model_name='feeinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='fee_installment_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='feemodule',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_fee_module_per_year'),
        ),
        migrations.AddConstraint(
            model_name='classfeeitem',
            constraint=models.UniqueConstraint(fields=('plan', 'fee_module'), name='unique_fee_module_per_class_plan'),
        ),
        migrations.AddConstraint(
            model_name='classfeeitem',
            constraint=models.CheckConstraint(condition=models.Q(('male_amount__gte', 0)), name='class_fee_male_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classfeeitem',
            constraint=models.CheckConstraint(condition=models.Q(('female_amount__gte', 0)), name='class_fee_female_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_payment_amount_positive'),
        ),
        migrations.DeleteModel(
            name='TuitionFeeRule',
        ),
        migrations.DeleteModel(
            name='TuitionInstallment',
        ),
        migrations.DeleteModel(
            name='TuitionPayment',
        ),
    ]
