# Generated by Django 6.0.6 on 2026-06-29 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0037_customuser_primary_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'catégorie de dépense',
                'verbose_name_plural': 'catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('beneficiary', models.CharField(blank=True, max_length=180, verbose_name='bénéficiaire ou fournisseur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('expense_date', models.DateField(verbose_name='date de dépense')),
                ('method', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('banque', 'Banque'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='ekdschoolmanager.academicyear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='ekdschoolmanager.expensecategory')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_school_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'dépense scolaire',
                'verbose_name_plural': 'dépenses scolaires',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_expense_category_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='school_expense_amount_positive'),
        ),
    ]
