# Generated by Django 6.0.6 on 2026-06-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0038_expensecategory_schoolexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ekdschoolmanager.academicyear')),
            ],
            options={
                'verbose_name': 'session académique',
                'verbose_name_plural': 'sessions académiques',
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_session_name_per_year'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year',), name='one_active_session_per_year'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academic_session_end_after_start')],
            },
        ),
    ]
