# Generated by Django 6.0.6 on 2026-06-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0039_academicsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='clôturée'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_closed', True), _negated=True), name='closed_session_cannot_be_active'),
        ),
    ]
