# Generated by Django 6.0.6 on 2026-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0040_academicsession_closed_session_cannot_be_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
