# Generated by Django 6.0.6 on 2026-06-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0041_alter_academicsession_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicsession',
            name='one_active_session_per_year',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='classes',
            field=models.ManyToManyField(related_name='academic_sessions', to='ekdschoolmanager.schoolclass', verbose_name='classes concernées'),
        ),
    ]
