# Generated by Django 6.0.6 on 2026-06-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0042_remove_academicsession_one_active_session_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicsession',
            name='academic_session_end_after_start',
        ),
    ]
