# Generated by Django 6.0.6 on 2026-06-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0044_academicsession_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(choices=[('equal', 'Même poids pour chaque ligne'), ('weighted', 'Pourcentage par ligne'), ('groups', 'Moyenne des groupes')], default='equal', max_length=12, verbose_name='mode de calcul')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grade_schemes', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scheme', to='ekdschoolmanager.academicsession')),
            ],
        ),
        migrations.CreateModel(
            name='GradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pourcentage')),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='note maximale')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ekdschoolmanager.gradegroup')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ekdschoolmanager.gradescheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gradegroup',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ekdschoolmanager.gradescheme'),
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='note')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='ekdschoolmanager.classsubject')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='ekdschoolmanager.studentenrollment')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_grades', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ekdschoolmanager.gradeline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('line', 'enrollment', 'class_subject'), name='unique_grade_entry'), models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='grade_entry_score_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradeline',
            constraint=models.UniqueConstraint(fields=('scheme', 'name'), name='unique_grade_line_name'),
        ),
        migrations.AddConstraint(
            model_name='gradeline',
            constraint=models.UniqueConstraint(fields=('scheme', 'order'), name='unique_grade_line_order'),
        ),
        migrations.AddConstraint(
            model_name='gradeline',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='grade_line_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='gradeline',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), models.Q(('weight__gt', 0), ('weight__lte', 100)), _connector='OR'), name='grade_line_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='gradegroup',
            constraint=models.UniqueConstraint(fields=('scheme', 'name'), name='unique_grade_group_name'),
        ),
        migrations.AddConstraint(
            model_name='gradegroup',
            constraint=models.UniqueConstraint(fields=('scheme', 'order'), name='unique_grade_group_order'),
        ),
    ]
