# Generated by Django 6.0.6 on 2026-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0045_gradegroup_gradescheme_gradeline_gradegroup_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradegroup',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pourcentage'),
        ),
        migrations.AddConstraint(
            model_name='gradegroup',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), models.Q(('weight__gt', 0), ('weight__lte', 100)), _connector='OR'), name='grade_group_weight_range'),
        ),
    ]
