# Generated by Django 6.0.6 on 2026-06-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0046_gradegroup_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('retard', 'Retard'), ('incident', 'Incident')], max_length=12, verbose_name='type')),
                ('occurred_on', models.DateField(verbose_name='date')),
                ('late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='heures de retard')),
                ('incident_type', models.CharField(blank=True, max_length=120, verbose_name='type d’incident')),
                ('severity', models.CharField(blank=True, choices=[('leger', 'Léger'), ('moyen', 'Moyen'), ('grave', 'Grave')], max_length=12, verbose_name='gravité')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('action_taken', models.TextField(blank=True, verbose_name='mesure prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='ekdschoolmanager.academicyear')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='ekdschoolmanager.studentenrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_discipline_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'entrée de discipline',
                'verbose_name_plural': 'entrées de discipline',
                'ordering': ['-occurred_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('late_hours__gte', 0)), name='discipline_record_late_hours_positive')],
            },
        ),
    ]
