# Generated by Django 6.0.6 on 2026-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0047_disciplinerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='entry_type',
            field=models.CharField(choices=[('retard', 'Retard'), ('absence', 'Absence'), ('incident', 'Incident')], max_length=12, verbose_name='type'),
        ),
    ]
