# Generated by Django 6.0.7 on 2026-07-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0048_alter_disciplinerecord_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/signatures/', verbose_name='signature'),
        ),
    ]
