# Generated by Django 6.0.7 on 2026-08-07 00:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0049_customuser_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superutilisateur'), ('admin', 'Administrateur'), ('proprietaire', 'Propriétaire'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('censeur', 'Censeur'), ('proviseur', 'Proviseur'), ('surveillant', 'Surveillant'), ('personnel', 'Personnel')], default='personnel', max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superutilisateur'), ('admin', 'Administrateur'), ('proprietaire', 'Propriétaire'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('censeur', 'Censeur'), ('proviseur', 'Proviseur'), ('surveillant', 'Surveillant'), ('personnel', 'Personnel')], max_length=20, verbose_name='rôle'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=12, verbose_name='statut')),
                ('days_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='jours par semaine')),
                ('period_duration', models.PositiveSmallIntegerField(default=60, verbose_name='durée d’un créneau (minutes)')),
                ('morning_start', models.TimeField(default=datetime.time(7, 0), verbose_name='début de la matinée')),
                ('morning_end', models.TimeField(default=datetime.time(12, 0), verbose_name='fin de la matinée')),
                ('afternoon_start', models.TimeField(default=datetime.time(15, 0), verbose_name='début de l’après-midi')),
                ('afternoon_end', models.TimeField(default=datetime.time(18, 0), verbose_name='fin de l’après-midi')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='ekdschoolmanager.academicyear')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_timetables', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='ekdschoolmanager.classsubject')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='ekdschoolmanager.schoolclass')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ekdschoolmanager.timetable')),
            ],
            options={
                'verbose_name': 'créneau d’emploi du temps',
                'verbose_name_plural': 'créneaux d’emploi du temps',
                'ordering': ['day', 'start_time', 'school_class__group'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year'), name='unique_timetable_per_school_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('timetable', 'school_class', 'day', 'start_time'), name='unique_class_slot_per_time'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timetable_slot_end_after_start'),
        ),
    ]
