# Generated by Django 6.0.7 on 2026-08-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0050_alter_customuser_role_alter_schoolmembership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='enforce_day_spacing',
            field=models.BooleanField(default=True, verbose_name='espacer d’au moins un jour les deux premières séances'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='enforce_max_two_hours',
            field=models.BooleanField(default=True, verbose_name='jamais plus de 2h d’une matière le même jour'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='enforce_paired_hours',
            field=models.BooleanField(default=True, verbose_name='regrouper les heures par blocs de 2h (lycée)'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='enforce_single_hour_middle',
            field=models.BooleanField(default=True, verbose_name='1h par jour au collège'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='skip_primary',
            field=models.BooleanField(default=True, verbose_name='ne pas générer pour le cycle primaire'),
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=60, verbose_name='libellé')),
                ('kind', models.CharField(choices=[('cours', 'Cours'), ('pause', 'Pause')], default='cours', max_length=8, verbose_name='type')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='ekdschoolmanager.timetable')),
            ],
            options={
                'verbose_name': 'créneau horaire',
                'verbose_name_plural': 'créneaux horaires',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPeriodRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Laisser vide pour interdire ce créneau tous les jours.', null=True, verbose_name='jour')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_restrictions', to='ekdschoolmanager.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='ekdschoolmanager.timetable')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='ekdschoolmanager.timetableperiod')),
            ],
            options={
                'verbose_name': 'interdiction de créneau',
                'verbose_name_plural': 'interdictions de créneaux',
                'ordering': ['subject__name', 'period__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.UniqueConstraint(fields=('timetable', 'order'), name='unique_period_order_per_timetable'),
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.UniqueConstraint(fields=('timetable', 'start_time'), name='unique_period_start_per_timetable'),
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timetable_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='subjectperiodrestriction',
            constraint=models.UniqueConstraint(fields=('timetable', 'subject', 'period', 'day'), name='unique_subject_period_restriction'),
        ),
    ]
