# Generated by Django 6.0.7 on 2026-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0051_timetable_enforce_day_spacing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='days_without_afternoon',
            field=models.JSONField(blank=True, default=list, help_text='Indices des jours (0 = lundi) où les créneaux d’après-midi restent vides.', verbose_name='jours sans cours l’après-midi'),
        ),
    ]
