# Generated by Django 6.0.7 on 2026-08-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0052_timetable_days_without_afternoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTimetableRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.BooleanField(default=False, help_text='La matière n’est pas placée dans l’emploi du temps.', verbose_name='exclue de la génération')),
                ('classes_per_session', models.PositiveSmallIntegerField(default=1, help_text='Nombre de classes qu’un enseignant peut prendre en même temps.', verbose_name='classes réunies par séance')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_rules', to='ekdschoolmanager.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='ekdschoolmanager.timetable')),
            ],
            options={
                'verbose_name': 'réglage de matière',
                'verbose_name_plural': 'réglages de matières',
                'ordering': ['subject__name'],
                'constraints': [models.UniqueConstraint(fields=('timetable', 'subject'), name='unique_subject_rule_per_timetable'), models.CheckConstraint(condition=models.Q(('classes_per_session__gte', 1)), name='subject_rule_classes_per_session_positive')],
            },
        ),
    ]
