# Generated by Django 6.0.7 on 2026-08-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0053_subjecttimetablerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_categories', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'type de matière',
                'verbose_name_plural': 'types de matières',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='ekdschoolmanager.subjectcategory', verbose_name='type de matière'),
        ),
        migrations.AddConstraint(
            model_name='subjectcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_category_per_school'),
        ),
    ]
