# Generated by Django 6.0.7 on 2026-08-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0054_subjectcategory_subject_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'regroupement de classes',
                'verbose_name_plural': 'regroupements de classes',
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedTimetableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'classe exclue de l’emploi du temps',
                'verbose_name_plural': 'classes exclues de l’emploi du temps',
                'ordering': ['school_class__group'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='subjecttimetablerule',
            name='unique_subject_rule_per_timetable',
        ),
        migrations.RemoveConstraint(
            model_name='subjecttimetablerule',
            name='subject_rule_classes_per_session_positive',
        ),
        migrations.AddField(
            model_name='classgroupsession',
            name='classes',
            field=models.ManyToManyField(related_name='timetable_groups', to='ekdschoolmanager.schoolclass', verbose_name='classes réunies'),
        ),
        migrations.AddField(
            model_name='classgroupsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='ekdschoolmanager.subject'),
        ),
        migrations.AddField(
            model_name='classgroupsession',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='ekdschoolmanager.timetable'),
        ),
        migrations.AddField(
            model_name='excludedtimetableclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_exclusions', to='ekdschoolmanager.schoolclass'),
        ),
        migrations.AddField(
            model_name='excludedtimetableclass',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_classes', to='ekdschoolmanager.timetable'),
        ),
        migrations.RemoveField(
            model_name='subjecttimetablerule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttimetablerule',
            name='timetable',
        ),
        migrations.AddConstraint(
            model_name='excludedtimetableclass',
            constraint=models.UniqueConstraint(fields=('timetable', 'school_class'), name='unique_excluded_class_per_timetable'),
        ),
        migrations.DeleteModel(
            name='SubjectTimetableRule',
        ),
    ]
