# Generated by Django 6.0.6 on 2026-08-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0056_exclusion_par_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_direction',
            field=models.CharField(blank=True, max_length=160, verbose_name='direction régionale'),
        ),
        migrations.AddField(
            model_name='school',
            name='inspection',
            field=models.CharField(blank=True, max_length=160, verbose_name='inspection'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=120, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=80, verbose_name='téléphone'),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_box',
            field=models.CharField(blank=True, max_length=80, verbose_name='boîte postale'),
        ),
        migrations.CreateModel(
            name='ReportCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_score_detail', models.BooleanField(default=True, help_text='Affiche chaque ligne de note (interrogation, devoir…) en plus de la moyenne.', verbose_name='afficher le détail des notes')),
                ('group_by_category', models.BooleanField(default=True, help_text='Regroupe les matières par type, avec un sous-total par groupe.', verbose_name='regrouper par type de matière')),
                ('show_rank', models.BooleanField(default=True, verbose_name='afficher le rang')),
                ('show_teacher', models.BooleanField(default=True, verbose_name='afficher le professeur')),
                ('show_appreciation', models.BooleanField(default=True, verbose_name='afficher l’appréciation')),
                ('show_class_statistics', models.BooleanField(default=True, help_text='Plus forte moyenne, plus faible moyenne et moyenne générale de la classe.', verbose_name='afficher les statistiques de classe')),
                ('council_note', models.TextField(blank=True, verbose_name='mention du conseil')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_settings', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'paramétrage des bulletins',
                'verbose_name_plural': 'paramétrages des bulletins',
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, verbose_name='contenu')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moyenne générale')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='rang')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='généré le')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='ekdschoolmanager.studentenrollment')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='ekdschoolmanager.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='ekdschoolmanager.academicsession')),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['school_class__group', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('session', 'enrollment'), name='unique_report_card_per_session')],
            },
        ),
        migrations.CreateModel(
            name='ReportCardAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='libellé')),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='note minimale')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_appreciations', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'appréciation de bulletin',
                'verbose_name_plural': 'appréciations de bulletin',
                'ordering': ['-minimum'],
                'constraints': [models.UniqueConstraint(fields=('school', 'label'), name='unique_appreciation_per_school'), models.CheckConstraint(condition=models.Q(('minimum__gte', 0), ('minimum__lte', 20)), name='appreciation_minimum_within_scale')],
            },
        ),
    ]
