# Generated by Django 6.0.6 on 2026-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0057_school_city_school_education_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'type de matière', 'verbose_name_plural': 'types de matières'},
        ),
        migrations.RemoveField(
            model_name='subjectcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
    ]
