# Generated by Django 6.0.6 on 2026-08-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0058_alter_subjectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ['name'], 'verbose_name': 'type de matière', 'verbose_name_plural': 'types de matières'},
        ),
        migrations.RemoveField(
            model_name='subjectcategory',
            name='order',
        ),
        migrations.CreateModel(
            name='SubjectCategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='nom de la règle')),
                ('scope', models.CharField(choices=[('ecole', 'Tout l’établissement'), ('cycle', 'Un cycle'), ('serie', 'Une série'), ('classes', 'Des classes choisies')], default='ecole', max_length=10, verbose_name='portée')),
                ('stage', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], max_length=12, verbose_name='cycle')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='série')),
                ('categories', models.JSONField(default=list, verbose_name='ordre des types')),
                ('classes', models.ManyToManyField(blank=True, related_name='category_orders', to='ekdschoolmanager.schoolclass', verbose_name='classes visées')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_orders', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'ordre des types de matières',
                'verbose_name_plural': 'ordres des types de matières',
                'ordering': ['scope', 'name'],
            },
        ),
    ]
