# Generated by Django 6.0.6 on 2026-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0059_alter_subjectcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cabinet',
            field=models.CharField(blank=True, max_length=160, verbose_name='cabinet'),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, default='RÉPUBLIQUE TOGOLAISE', max_length=120, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='school',
            name='country_motto',
            field=models.CharField(blank=True, default='Travail — Liberté — Patrie', max_length=160, verbose_name='devise nationale'),
        ),
        migrations.AddField(
            model_name='school',
            name='direction_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='ville de la direction'),
        ),
        migrations.AddField(
            model_name='school',
            name='general_secretariat',
            field=models.CharField(blank=True, max_length=160, verbose_name='secrétariat général'),
        ),
        migrations.AddField(
            model_name='school',
            name='ministry',
            field=models.CharField(blank=True, default='MINISTÈRE DE L’ÉDUCATION NATIONALE', max_length=200, verbose_name='ministère'),
        ),
    ]
