# Generated by Django 6.0.6 on 2026-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0060_school_cabinet_school_country_school_country_motto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsettings',
            name='template',
            field=models.CharField(choices=[('standard', 'Standard'), ('officiel', 'Officiel (compact)')], default='standard', help_text='Disposition imprimée. Le modèle officiel reprend la maquette administrative : une seule grille de notes et un pied de page récapitulatif (trimestres, absences, décision du conseil).', max_length=12, verbose_name='modèle de bulletin'),
        ),
    ]
