# Generated by Django 6.0.6 on 2026-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0061_reportcardsettings_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsettings',
            name='watermark',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('mosaique', 'Mosaïque (texte répété)'), ('diagonale', 'Bandeau en diagonale'), ('logo', 'Logo en fond')], default='aucun', help_text='Marque de fond imprimée derrière le bulletin, contre la photocopie.', max_length=12, verbose_name='filigrane'),
        ),
        migrations.AddField(
            model_name='reportcardsettings',
            name='watermark_source',
            field=models.CharField(choices=[('nom', 'Nom de l’établissement'), ('code', 'Code de l’établissement')], default='nom', help_text='Texte repris par le filigrane, sans effet sur le filigrane « logo ».', max_length=8, verbose_name='texte du filigrane'),
        ),
    ]
