# Generated by Django 6.0.6 on 2026-08-08 21:45

from django.db import migrations, models
from django.utils import timezone


def mark_existing_as_configured(apps, schema_editor):
    """Considère comme déjà réglés les paramétrages qui existent aujourd'hui.

    Une ligne de paramétrage n'est créée qu'au premier accès aux bulletins,
    souvent suivi d'un enregistrement. Les laisser à `NULL` reviendrait à
    rouvrir la porte au barème par défaut sur des écoles qui ont déjà fait
    leurs choix : on préfère figer l'existant, quitte à être conservateur.
    """
    ReportCardSettings = apps.get_model('ekdschoolmanager', 'ReportCardSettings')
    ReportCardSettings.objects.filter(configured_at__isnull=True).update(
        configured_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0062_reportcardsettings_watermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsettings',
            name='configured_at',
            field=models.DateTimeField(blank=True, help_text="Date du premier enregistrement manuel. Tant qu'elle est vide, l'établissement n'a jamais réglé ses bulletins et reçoit les valeurs d'usage ; une fois posée, plus rien ne modifie le paramétrage en dehors d'une saisie explicite.", null=True, verbose_name='enregistré le'),
        ),
        migrations.RunPython(
            mark_existing_as_configured,
            # Le retour arrière retire simplement la colonne : rien à défaire.
            migrations.RunPython.noop,
        ),
    ]
