# Generated by Django 6.0.6 on 2026-08-09 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0064_reportcardsettings_watermarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(verbose_name='date de l’appel')),
                ('period', models.CharField(blank=True, help_text='Créneau horaire ou moment de la journée, libre.', max_length=40, verbose_name='créneau')),
                ('note', models.TextField(blank=True, verbose_name='observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='ekdschoolmanager.academicyear')),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='ekdschoolmanager.classsubject', verbose_name='matière')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='ekdschoolmanager.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='ekdschoolmanager.schoolclass')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='fait par')),
            ],
            options={
                'verbose_name': 'appel',
                'verbose_name_plural': 'appels',
                'ordering': ['-taken_on', 'school_class__group'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('excuse', 'Absence justifiée')], default='present', max_length=10, verbose_name='statut')),
                ('minutes_late', models.PositiveSmallIntegerField(default=0, verbose_name='minutes de retard')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='ekdschoolmanager.studentenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ekdschoolmanager.attendancesession')),
            ],
            options={
                'verbose_name': 'présence',
                'verbose_name_plural': 'présences',
                'ordering': ['enrollment__student__last_name', 'enrollment__student__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('school_class', 'taken_on', 'class_subject', 'period'), name='unique_attendance_session_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'enrollment'), name='unique_attendance_per_student'),
        ),
    ]
