# Generated by Django 6.0.6 on 2026-08-11 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0065_attendancesession_attendancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('body', models.TextField(verbose_name='contenu')),
                ('audience', models.CharField(choices=[('tous', 'Tout l’établissement'), ('personnel', 'Le personnel'), ('roles', 'Certains rôles'), ('classes', 'Certaines classes')], default='tous', max_length=12, verbose_name='destinataires')),
                ('roles', models.JSONField(blank=True, default=list, verbose_name='rôles visés')),
                ('priority', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=12, verbose_name='priorité')),
                ('is_published', models.BooleanField(default=True, help_text='Une annonce non publiée reste un brouillon, visible de son seul auteur.', verbose_name='publiée')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publiée le')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='ekdschoolmanager.academicyear')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('classes', models.ManyToManyField(blank=True, related_name='announcements', to='ekdschoolmanager.schoolclass', verbose_name='classes visées')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='objet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernier message')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ekdschoolmanager.school')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ekdschoolmanager.conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='lu par')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='ekdschoolmanager.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lecture d’annonce',
                'verbose_name_plural': 'lectures d’annonces',
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read')],
            },
        ),
    ]
