# Generated by Django 6.0.6 on 2026-08-11 03:13

import django.db.models.deletion
import ekdschoolmanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0066_announcement_conversation_message_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ekdschoolmanager.models.message_attachment_path, verbose_name='fichier')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Message vocal'), ('document', 'Document')], default='document', max_length=10, verbose_name='type')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nom d’origine')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='type MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='taille')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ekdschoolmanager.message')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['id'],
            },
        ),
    ]
