# Generated by Django 6.0.6 on 2026-08-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0067_alter_message_body_messageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='clôturée le')),
                ('report_card_count', models.PositiveIntegerField(default=0, verbose_name='bulletins')),
                ('grade_entry_count', models.PositiveIntegerField(default=0, verbose_name='notes')),
                ('discipline_count', models.PositiveIntegerField(default=0, verbose_name='entrées de discipline')),
                ('attendance_session_count', models.PositiveIntegerField(default=0, verbose_name='appels')),
                ('attendance_record_count', models.PositiveIntegerField(default=0, verbose_name='présences')),
                ('payload', models.JSONField(default=dict, verbose_name='archive')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='clôturée par')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='ekdschoolmanager.academicsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'clôture de session',
                'verbose_name_plural': 'clôtures de session',
                'ordering': ['-closed_at'],
            },
        ),
    ]
