# Generated by Django 6.0.6 on 2026-08-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0068_sessionclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Les bulletins de cette session portent la moyenne annuelle.', verbose_name="dernière session de l'année"),
        ),
    ]
