# Generated by Django 6.0.6 on 2026-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0069_academicsession_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='établi le'),
        ),
    ]
