# Generated by Django 6.0.6 on 2026-08-24 16:40

from django.db import migrations, models

# Les quatre paliers d'examen du cursus togolais, par le nom que portent les
# niveaux déjà en base. Les abréviations couvrent les écoles qui ont saisi
# « Tle » ou « 1ère » plutôt que le nom complet.
EXAMS = {
    "cm2": "CEPD",
    "3ème": "BEPC", "3eme": "BEPC", "3e": "BEPC",
    "première": "BAC 1", "premiere": "BAC 1", "1ère": "BAC 1", "1ere": "BAC 1",
    "terminale": "BAC 2", "tle": "BAC 2",
}


def flag_exam_levels(apps, schema_editor):
    """Marque les niveaux d'examen des écoles déjà créées.

    Sans ce rattrapage, toute école existante partirait sans aucun niveau
    d'examen et ses terminales passeraient sur leur moyenne annuelle.
    """
    SchoolLevel = apps.get_model("ekdschoolmanager", "SchoolLevel")
    for level in SchoolLevel.objects.all():
        exam = EXAMS.get(level.name.strip().lower())
        if exam:
            level.is_exam_level = True
            level.exam_name = exam
            level.save(update_fields=["is_exam_level", "exam_name"])


def unflag_exam_levels(apps, schema_editor):
    """Retour arrière : les colonnes disparaissent, rien à défaire."""


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0070_reportcard_issued_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='exam_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="moyenne à l'examen"),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='exam_name',
            field=models.CharField(blank=True, default='', help_text="Nom de l'examen, écrit tel quel sur le bulletin (CEPD, BEPC, BAC 1…).", max_length=30, verbose_name='examen'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='is_exam_level',
            field=models.BooleanField(default=False, help_text="Niveau sanctionné par un examen officiel : la décision de fin d'année suit le résultat de l'examen.", verbose_name="classe d'examen"),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='passing_average',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4, verbose_name='moyenne de passage'),
        ),
        migrations.RunPython(flag_exam_levels, unflag_exam_levels),
    ]
