# Generated by Django 6.0.6 on 2026-08-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0071_reportcard_exam_average_schoollevel_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsettings',
            name='show_censor_name',
            field=models.BooleanField(default=False, help_text='Ajoute la signature du censeur au pied du bulletin.', verbose_name='nom du censeur'),
        ),
        migrations.AddField(
            model_name='reportcardsettings',
            name='show_founder_name',
            field=models.BooleanField(default=False, help_text="Ajoute la signature du fondateur — le propriétaire de l'établissement — au pied du bulletin.", verbose_name='nom du fondateur'),
        ),
        migrations.AddField(
            model_name='reportcardsettings',
            name='show_principal_name',
            field=models.BooleanField(default=True, help_text='Inscrit le nom du proviseur sous sa signature.', verbose_name='nom du proviseur'),
        ),
    ]
