# Generated by Django 6.0.6 on 2026-08-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0073_full_exam_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('redoublant', 'Redoublant'), ('abandon', 'Abandon'), ('titulaire_cepd', 'Titulaire du CEPD'), ('titulaire_bepc', 'Titulaire du BEPC'), ('bachelier', 'Bachelier'), ('diplome', 'Diplômé')], default='nouveau', max_length=20, verbose_name='statut de l’élève'),
        ),
        migrations.CreateModel(
            name='CarriedDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant dû')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant réglé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carried_debt', to='ekdschoolmanager.studentenrollment', verbose_name='inscription d’origine')),
                ('origin_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_debts', to='ekdschoolmanager.academicyear', verbose_name='année d’origine')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_debts', to='ekdschoolmanager.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_debts', to=settings.AUTH_USER_MODEL, verbose_name='élève')),
            ],
            options={
                'verbose_name': 'impayé reporté',
                'verbose_name_plural': 'impayés reportés',
                'ordering': ['origin_year__start_date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='CarriedDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('paid_on', models.DateField(verbose_name='date de paiement')),
                ('method', models.CharField(default='espece', max_length=20, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ekdschoolmanager.carrieddebt')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_debt_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versement sur impayé',
                'verbose_name_plural': 'versements sur impayés',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='clôturée le')),
                ('class_count', models.PositiveIntegerField(default=0, verbose_name='classes')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name='inscriptions')),
                ('promoted_count', models.PositiveIntegerField(default=0, verbose_name='passages')),
                ('repeated_count', models.PositiveIntegerField(default=0, verbose_name='redoublements')),
                ('graduated_count', models.PositiveIntegerField(default=0, verbose_name='sorties diplômées')),
                ('unassigned_count', models.PositiveIntegerField(default=0, verbose_name='sans classe')),
                ('undecided_count', models.PositiveIntegerField(default=0, verbose_name='sans décision')),
                ('carried_debt_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='impayés reportés')),
                ('payload', models.JSONField(default=dict, verbose_name='archive')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='ekdschoolmanager.academicyear', verbose_name='année académique')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_years', to=settings.AUTH_USER_MODEL, verbose_name='clôturée par')),
                ('next_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_closures', to='ekdschoolmanager.academicyear', verbose_name='année suivante')),
            ],
            options={
                'verbose_name': 'clôture d’année',
                'verbose_name_plural': 'clôtures d’année',
                'ordering': ['-closed_at'],
            },
        ),
    ]
