# Generated by Django 6.0.6 on 2026-08-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0074_alter_customuser_student_status_carrieddebt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearclosure',
            name='attendance_record_count',
            field=models.PositiveIntegerField(default=0, verbose_name='présences'),
        ),
        migrations.AddField(
            model_name='yearclosure',
            name='attendance_session_count',
            field=models.PositiveIntegerField(default=0, verbose_name='appels'),
        ),
        migrations.AddField(
            model_name='yearclosure',
            name='discipline_count',
            field=models.PositiveIntegerField(default=0, verbose_name='entrées de discipline'),
        ),
    ]
