# Generated by Django 6.0.6 on 2026-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0075_yearclosure_attendance_record_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearclosure',
            name='copied_class_count',
            field=models.PositiveIntegerField(default=0, verbose_name='classes reconduites'),
        ),
        migrations.AddField(
            model_name='yearclosure',
            name='copied_fee_plan_count',
            field=models.PositiveIntegerField(default=0, verbose_name='barèmes reconduits'),
        ),
        migrations.AddField(
            model_name='yearclosure',
            name='copied_subject_count',
            field=models.PositiveIntegerField(default=0, verbose_name='matières reconduites'),
        ),
    ]
