# Generated by Django 6.0.6 on 2026-08-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0076_yearclosure_copied_class_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='maximum_capacity',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='capacité maximale'),
        ),
    ]
