# Generated by Django 6.0.6 on 2026-08-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0077_alter_schoolclass_maximum_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youngest_first', models.BooleanField(default=True, help_text="À moyenne égale, l'élève le plus jeune passe devant. Les plus âgés se retrouvent donc dans les dernières classes.", verbose_name='les moins âgés dans les premières classes')),
                ('best_first', models.BooleanField(default=True, help_text="Les élèves sont rangés par moyenne décroissante avant d'être distribués, la première classe servie en premier.", verbose_name='les meilleures moyennes dans les premières classes')),
                ('balance_headcount', models.BooleanField(default=True, help_text='Chaque élève rejoint la classe la moins remplie de son niveau : les effectifs restent dans le même ordre de grandeur au lieu de remplir une classe avant la suivante.', verbose_name='équilibrer les effectifs')),
                ('balance_girls', models.BooleanField(default=True, help_text='Les filles sont réparties comme les effectifs, en tenant compte de celles déjà inscrites dans chaque classe.', verbose_name='équilibrer le nombre de filles')),
                ('reserved_excellent', models.PositiveSmallIntegerField(default=3, help_text="Nombre d'excellents élèves mis de côté pour chaque classe avant la distribution, en commençant par les dernières : sans cela, les meilleurs se concentrent tous devant. Zéro désactive la réserve.", verbose_name='excellents élèves réservés par classe')),
                ('excellent_minimum', models.DecimalField(decimal_places=2, default=16, help_text='Moyenne à partir de laquelle un élève entre dans la réserve.', max_digits=4, verbose_name="moyenne d'un excellent élève")),
                ('allow_overflow', models.BooleanField(default=True, help_text="Quand toutes les classes d'un niveau sont pleines et qu'il reste des élèves, la capacité maximale est dépassée plutôt que de les laisser sans classe.", verbose_name='dépasser légèrement la capacité')),
                ('overflow_margin', models.PositiveSmallIntegerField(default=5, help_text="Nombre de places ouvertes au-delà de la capacité maximale, et seulement quand il n'y a plus de place ailleurs.", verbose_name='dépassement toléré par classe')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignment_settings', to='ekdschoolmanager.school')),
            ],
            options={
                'verbose_name': 'règles de répartition',
                'verbose_name_plural': 'règles de répartition',
            },
        ),
    ]
