# Generated by Django 6.0.6 on 2026-08-25 10:46

import ekdschoolmanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0078_classassignmentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignmentsettings',
            name='band_limits',
            field=models.JSONField(blank=True, default=ekdschoolmanager.models.default_band_limits, help_text='Nombre maximal d\'élèves d\'une tranche de moyenne à placer dans une même classe, par borne basse de tranche : {"18": 2} limite à deux les élèves de 18 à 20 par classe. Zéro lève la limite. Elle cède plutôt que de laisser un élève sans classe.', verbose_name='maximum par tranche de moyenne'),
        ),
    ]
