# Generated by Django 6.0.6 on 2026-08-25 10:56

import ekdschoolmanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekdschoolmanager', '0079_classassignmentsettings_band_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignmentsettings',
            name='band_limits',
            field=models.JSONField(blank=True, default=ekdschoolmanager.models.default_band_limits, help_text='Nombre maximal d\'élèves d\'une tranche de moyenne à placer dans une même classe, niveau par niveau : {"7": {"18": 2}} limite à deux les élèves de 18 à 20 par classe du niveau 7. Une tranche absente ou à zéro n\'est pas limitée, et la limite cède plutôt que de laisser un élève sans classe.', verbose_name='maximum par tranche de moyenne'),
        ),
    ]
